# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "CCPELib"
description = "Yet another PE file manipulation library."

[target.CCPELib]
type = "library"
headers = ["include/**.h"]
sources = ["src/**.cpp", "src/**.h"]
include-directories = ["include"]
