# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "CCPELib"
description = "Yet another PE file manipulation library."
languages = ["CXX"]
include-before = [
	"configurations.cmake"
]

[subdir.test]

[target.linux-pe]
type = "interface"
include-directories = ["linux-pe/includes"]
compile-features = ["cxx_std_20"]

[target.CCPELib]
type = "library"
headers = ["include/**.h"]
sources = ["src/**.cpp", "src/**.h"]
include-directories = ["include"]
link-libraries = ["linux-pe"]
compile-features = ["cxx_std_20"]
