name: CMake-win

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2019]
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
          submodules: 'recursive'
          
    - name: Build32
      run: |
        cmake -B build32 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -AWin32
        cmake --build build32 --config ${{ env.BUILD_TYPE }} --parallel
    
    - name: Upload artifacts-32
      uses: actions/upload-artifact@main
      with:
        name: CCPELib-32
        path: |
          include/*
          build32/Release/*
    
    - name: Build64
      run: |
        cmake -B build64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build64 --config ${{ env.BUILD_TYPE }} --parallel
    
    - name: Upload artifacts-64
      uses: actions/upload-artifact@main
      with:
        name: CCPELib-64
        path: |
          include/*
          build64/Release/*      
